name: "[Called] TFSec Security Scan"

on:
  workflow_call:
    inputs:
      environment:
        description: "Target deployment environment"
        required: true
        type: string
      working_directory:
        description: "Terraform working directory"
        required: false
        default: "."
        type: string
    secrets:
      TF_API_TOKEN:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_CLIENT_ID:
        required: true
      ARM_TENANT_ID:
        required: true

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    container:
      image: aquasec/trivy:0.55.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: List Files for Debug
        run: ls -R /__w/project2/project2/
        
      - name: Run Scan and Show Summary
        run: |
          run: |
          echo "### Trivy Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          trivy fs --scanners misconfig --severity HIGH,CRITICAL --format table /__w/project2/project2/ >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
