name: "[Called] Manual Validation"

on:
  workflow_call:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: string
        
    secrets:
      TF_API_TOKEN:
        required: false
      ARM_SUBSCRIPTION_ID:
        required: false
      ARM_CLIENT_ID:
        required: false
      ARM_TENANT_ID:
        required: false
jobs:
  manual-approval:
    runs-on: ubuntu-latest
    environment: approval
    steps:
      - name: Wait for Approval
        run: echo "Manual approval received, proceeding with deployment."
