name: "docker-tflint"

on:
  workflow_call:
    inputs:
      environment:
        description: "Target deployment environment"
        required: true
        type: string
      working_directory:
        description: "Terraform working directory"
        required: false
        default: "."
        type: string
    secrets:
      TF_API_TOKEN:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_CLIENT_ID:
        required: true
      ARM_TENANT_ID:
        required: true       
      
        
permissions:
  id-token: write
  contents: read           
env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      TF_WORKSPACE: statefile-${{ inputs.environment }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_USE_OIDC: "true"  

jobs:
  tflint:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/terraform-linters/tflint:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: TFLint Run
        run: |
          tflint \
            --chdir=${{ inputs.working_directory }} \
            --recursive \
            --format compact > tflint-report.txt || true
          echo "--- TFLint Summary ---"


      
