name: "[Called] Terraform Apply"

on:
  workflow_call:
    inputs:
      environment:
        description: "Target deployment environment"
        required: true
        type: string
      working_directory:
        description: "Terraform working directory"
        required: false
        default: "."
        type: string
    secrets:
      TF_API_TOKEN:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_CLIENT_ID:
        required: true
      ARM_TENANT_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    container:
      image: hashicorp/terraform:1.13.0

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      TF_WORKSPACE: statefile-${{ inputs.environment }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_USE_OIDC: "true"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download tfplan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-json-${{ inputs.environment }}
          path: ${{ inputs.working_directory }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Job Summary
        if: always()
        run: |
          echo "# Terraform Apply Completed" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment:** ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
